### ISSUE TITLE
fluentd configmap is created even if fluentd is not set

### ISSUE THREAD

**Issue by tbondarchuk** [hyperledger-labs/fabric-operator#100]
sample-network does not have fluentd configured in CRDs, so fluentd container is not present in pods but fluentd configmaps are still created and mounted as volumes:

```
        volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: org2-peer1-statedb-pvc
        - name: fabric-peer-0
          persistentVolumeClaim:
            claimName: org2-peer1-pvc
        - configMap:
            defaultMode: 420
            name: org2-peer1-fluentd
          name: fluentd-config
```
