### ISSUE TITLE
Add support for custom pod properties to crd

### ISSUE THREAD

**Issue by tbondarchuk** [hyperledger-labs/fabric-operator#96]
Currently there are no way to pass custom pod configs via crds, like nodeSelector/tolerations/topologySpreadConstraints/affinity/etc (unless I'm missing something?)

There is only arch/zone/region though not sure what exactly they configure, labels?

**Comment by tbondarchuk** [comment]
Was able to trace to here:

https://github.com/hyperledger-labs/fabric-operator/blob/03d6f432313596d877c61979ac661d6d26b9afd7/pkg/offering/base/peer/override/deployment.go#L799

nothing for toleration or custom labels for nodeSelector.

Also - sample-network creates pods with quite inconsistent affinity:

ca
```        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - org0-ca
                topologyKey: topology.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - org0-ca
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
```

orderer
```
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: orgname
                    operator: In
                    values:
                    - OrdererOrg
                topologyKey: kubernetes.io/hostname
              weight: 100
````

peer
```
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: orgname
                    operator: In
                    values:
                    - Org1MSP
                topologyKey: kubernetes.io/hostname
              weight: 100
```
